# Generated by Django 2.2 on 2020-02-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buddy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
